### ISSUE TITLE
ffmpeg undefined

### ISSUE THREAD

**Issue by Malaber** [Inrixia/Floatplane-Downloader#227]
I am getting the following error in the log: 

```
floatplane-downloader  | [12/12/2024, 2:20:09 PM] First Segway Segue, Pulling a Truck using MCM and Linus' car getting Towed! - BTS Part 7 - Download complete!
floatplane-downloader  | [12/12/2024, 2:20:09 PM] First Segway Segue, Pulling a Truck using MCM and Linus' car getting Towed! - BTS Part 7 - Muxing ffmpeg metadata...
floatplane-downloader  | [12/12/2024, 2:20:09 PM] First Segway Segue, Pulling a Truck using MCM and Linus' car getting Towed! - BTS Part 7 - An error occoured: Muxing ffmpeg metadata - Cannot mux ffmpeg metadata! Video not downloaded.
floatplane-downloader  | [First Segway Segue, Pulling a Truck using MCM and Linus' car getting Towed! - BTS Part 7] undefined
```

Pretty sure this is a permission problem, but I don't know how to solve it. Can I get more detailed logs what failed?

I am mounting a hard drive mounted at /mnt/hdd which is also mounted in another docker container (plex).

**Comment by Inrixia** [comment]
Most likely a file systems permission issue as the file does not exist after downloading to mux.

Probably check your docker config/mount settings etc.

**Comment by Malaber** [comment]
Is there any way to put the downloader into debug mode or something? I don't really know how I should troubleshoot this now. 

```
services:
  floatplane-downloader:
    image: inrix/floatplane-downloader:dev
    platform: linux/x86_64
    container_name: floatplane-downloader
    environment:
      - headless=true
    volumes:
      - ./data/db:/fp/db
      - /mnt/hdd/VideoStation/YouTube/:/fp/videos
    restart: unless-stopped
```

these are my settings, the files it creates are created as root: 

```
daniel@sprintsteak:/srv/docker/floatplane-downloader$ ls -la /mnt/hdd/VideoStation/YouTube/FP\ Exclusives/
total 1838928
drwxr-xr-x  2 root      root           4096 Dec 12 14:23  .
drwxrwxrwx 10 syncthing syncthing      4096 Dec 12 14:15  ..
-rw-r--r--  1 root      root         202710 Nov 13 19:05 'FP Exclusives - S2024E1113190500 - Writers Showcase Their First Script Elijah Horner.jpeg'
-rw-r--r--  1 root      root            768 Nov 13 19:05 'FP Exclusives - S2024E1113190500 - Writers Showcase Their First Script Elijah Horner.nfo'
-rw-r--r--  1 root      root       28458371 Dec 12 14:23 'FP Exclusives - S2024E1113190500 - Writers Showcase Their First Script Elijah Horner.partial'
-rw-r--r--  1 root      root         594191 Nov 14 17:35 'FP Exclusives - S2024E1114173500 - Extras AMD Upgrade Andrew Moore.jpeg'
-rw-r--r--  1 root      root            458 Nov 14 17:35 'FP Exclusives - S2024E1114173500 - Extras AMD Upgrade Andrew Moore.nfo'
-rw-r--r--  1 root      root       74808707 Dec 12 14:23 'FP Exclusives - S2024E1114173500 - Extras AMD Upgrade Andrew Moore.partial'
```
